language: android
android:
  components:
    - build-tools-19.1.0
    - android-18
    - sysimg-18
    - extra-android-support
  licenses:
    - android-sdk-license-5be876d5
    - '.*intel.+'

before_install:
  - android list sdk --no-ui --all --extended

script:
    - ./gradlew connectedAndroidTestStagingDebug
